=== Cloud-DevOps/OCF-spec/ra/ra-ap-1.dtd
<?xml version="1.0" ?>

<!ELEMENT resource-agent (version,executable,provides?,parameters,actions) >
<!ATTLIST resource-agent
	name	CDATA	#REQUIRED>

<!ELEMENT version (#PCDATA)>

<!ELEMENT executable (#PCDATA)>

<!ELEMENT provides (#PCDATA)>

<!ELEMENT parameters (parameter*)>

<!ELEMENT actions (action*)>

<!ELEMENT parameter (longdesc+,shortdesc+,content,dependency?)>
<!ATTLIST parameter
	name	CDATA	#REQUIRED
	resource-key	(1|0)	"0">

<!ELEMENT longdesc ANY>
<!ATTLIST longdesc
	lang	NMTOKEN	#IMPLIED>

<!ELEMENT shortdesc ANY>
<!ATTLIST shortdesc
	lang	NMTOKEN	#IMPLIED>

<!ELEMENT content EMPTY>
<!ATTLIST content
	type	CDATA	#REQUIRED
	format	CDATA	#IMPLIED
	default CDATA	#IMPLIED>

<!ELEMENT dependency EMPTY>
<!ATTLIST dependency
	type	CDATA	#REQUIRED>

<!ELEMENT action EMPTY>
<!ATTLIST action
	name	(start|stop|restart|status|reload)	#REQUIRED
	timeout		CDATA	#REQUIRED
	tries		CDATA	#IMPLIED
	interval 	CDATA	#IMPLIED
	start-delay 	CDATA	#IMPLIED>

=== Cloud-DevOps/OCF-spec/ra/ra-metadata-example.xml
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "http://www.opencf.org/standards/ra-ap-1.dtd">

<!-- Root element: give the name of the Resource agent -->
<resource-agent name="Filesystem">

<!-- Version number of the standard this complies with -->
<version>1.1</version>

<!-- A full pathname to the RA executable -->
<executable>/usr/ocf/sbin/filesystem"</executable>

<!-- In addition to providing our own type, we might provide an abstract
     class; this doesn't make much sense here; it is an optional element
     and just included for completeness. -->
<provides>Mountpoint</provides>
 
<!-- List all the instance parameters the RA supports or requires. -->
<parameters>

<!-- Note that there should be only one parameter with the resource-key flag
     set; this signifies this is the one describing the resource name.
 -->
 
<parameter name="Mountpoint" resource-key="1">
<!-- This is the long, helpful description of what the parameter is all
     about. A user interface might display it to the user if he asks for 
     elaborate help with an option, and it would obviously also provide 
     examples etc.
     
     You can have multiple ones with different "lang" attributes, but this is
     not required.
-->
<longdesc lang="en">
The resource name is the directory where the filesystem will be actually mounted. 
Please make sure it exists.
</longdesc>

<!-- The shortdesc may be displayed by the resource manager as a tooltip or
     equivalent -->
<shortdesc>Mountpoint</shortdesc>

<!-- Further definition of the content; used by a GUI or something for
     verifying user input. -->
<content type="string" format="^/[:alnum:]+$" default="/mnt" />

</parameter>

<parameter name="Device">
<longdesc>
When mounting a filesystem on a specific mountpoint, you have to specify which
device should be mounted; this will usually be similiar to /dev/sda1 or
/dev/volumegroup/logicalvolume when using LVM.
</longdesc>
<shortdesc>Device to be mounted</shortdesc>
<content type="string" format="^/dev/"/>
<!-- This is a dependency on a "Blockdevice" resource; instead of specifying
     the Device manually, the adminstrator could set the dependency and the
     RM would provide the resource name of the dependency as the parameter
     value. -->
<dependency type="Blockdevice"/>
</parameter>

<parameter name="FSType">
<longdesc>
You should chose a journaled filesystem for the shared storage to ensure that
the filesystem remains consistent and that it can be mounted without an
expensive fsck run; recommendations include reiserfs, ext3 and XFS.
</longdesc>
<shortdesc>Type of the filesystem</shortdesc>
<content type="enum" format="reiserfs,ext2,ext3,jfs,xfs" default="reiserfs"/>
</parameter>

<parameter name="mount_options">
<longdesc>
The mount options used for mounting a filesystem; normally this is set to
defaults, but you may want to modify this if you require a read-only
mount or something similar.
</longdesc>
<shortdesc>Mount options for this filesystem</shortdesc>
<content type="string" default="defaults" />
</parameter>

</parameters>

<!-- List the actions supported by the RA -->
<actions>
<!-- Valid actions: start, stop, restart, status, reload
     The timeout is given in seconds.
  -->
<action name="start"   timeout="200" />
<action name="stop"    timeout="100" />
<!-- This is a mandatory action, but the RA suggests to the RM that
     it doesn't make sense. -->
<action name="restart" timeout="150" tries="0" />
<action name="status"  timeout="60" interval="30" start-delay="50" />
<!-- If the RA _does_ support the graceful reload of its configuration on
     request, it should advertise the reload action here; this is an optional
     element! -->
<action name="reload"  timeout="60" />

</actions>

</resource-agent>
